### ISSUE TITLE
Script works for RSPD 3303X-E (product of RS PRO)

### ISSUE THREAD

**Issue by ca1991126** [geissdoerfer/python-spd3303x#3]
Hi, there,

Thanks a lot for your effort for maintain such a fancy script. I have a power supply RSPD 3303X-E (one product of RS-PRO, https://de.rs-online.com/web/p/labornetzgerate/1236468) on hand, and it verified that the script works perfectly on the machine also. The precondition is I need add device model (NPD3XHBC4R0026) to list "KNOWN_MODELS" and dictionary "MANUFACTURERS".

    KNOWN_MODELS = [
        "SPD3303X",
        "SPD3303X-E",
        "SPD3XIDD5R7170",
        "NPD3XHBC4R0026",
    ]

    MANUFACTURERS = {
        "SPD3303X": "Siglent",
        "SPD3303X-E": "Siglent",
        # This one is called RSPD3303X-E by RS PRO.
        "SPD3XIDD5R7170": "[RS PRO]",
        "NPD3XHBC4R0026": "[RS PRO]",
    }

So if it is possible, you can add the device model in your module.

**Comment by geissdoerfer** [comment]
Hi, thanks for opening this issue. I've just added the changes you suggested to the `add_NPD3XHBC4R0026` branch. Can you please check if the code on this branch works with your device?

**Comment by ca1991126** [comment]
Hi, thanks for the rapid reply. I just test the new script on the machine, it works fine.

The issue can be closed.

**Comment by geissdoerfer** [comment]
OK thanks. The changes have been released on PyPi.
